# Settings for local machine. Needs to be adapted for each computer the anlysis has to run on. NEW USERS: make a local copy of this file called loc_settigs.yaml in the
# same folder as this and set the paths according to your local environment
---

# base directory for analysis code
base_dir: 'C:\Users\The_mothership\Documents\GitHub\JEDI\'

# destination for figures
figure_output_path: 'E:\JEDI_figures\'

...
